name: CD

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@master
        env:
          PW: ${{ secrets.PW }}
        with:
          key: ${{ secrets.SK }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          envs: PW
          script: |
            cd /usr/share/nginx/dogcat
            git pull origin main
            composer install -n --no-dev --prefer-dist
            echo $PW | sudo -S npm ci
            echo $PW | sudo -S npm run build
            php artisan migrate --force
            php artisan config:cache